# Linear Harmoic Oscillator - SKP

In [1]:
import numpy as np


In [2]:
import sympy as sp

In [ ]:
# add codes from 'QM1d_analysis_SKP.ipynb'

## Degeneracy and arrangement of states
Here a code is given which calcualtes the energy levels and corresponding quantum numbers of 3D harmonic oscillator (isotropic and anisotropic).

In [12]:
n1, n2, n3 = sp.symbols('n_1 n_2 n_3', real=True, negative=False)
hcut = sp.Symbol('hbar')
w1, w2, w3 = sp.symbols('omega_1 omega_2 omega_3', real=True)
En123 = (n1 +sp.Rational(1,2))*hcut*w1 +(n2 +sp.Rational(1,2))*hcut*w2 +(n3 +sp.Rational(1,2))*hcut*w3

In [19]:
En123.subs([(n1,1),(n2,2),(n3,5), (w1,1),(w2,1),(w3,1)])

19*hbar/2

In [46]:
Ens = []
ns = []
Ensval = []
n1max, n2max, n3max = 10, 10, 10         # INPUT
w1val, w2val, w3val = 1, 1, 1         # INPUT
for n1s in range(n1max+1):
    for n2s in range(n2max+1):
        for n3s in range(n3max+1):
            ns.append(n1s), ns.append(n2s), ns.append(n3s)
            ens = En123.subs([(n1,n1s),(n2,n2s),(n3,n3s), (w1,w1val),(w2,w2val),(w3,w3val)])
            Ens.append(ens)
            ensval = En123.subs([(n1,n1s),(n2,n2s),(n3,n3s), (w1,w1val),(w2,w2val),(w3,w3val),(hcut,1)])
            Ensval.append(ensval)
Ens = sp.Array(Ens)
Ensarr = np.array(Ensval)
nsarr = np.array(ns).reshape((Ensarr.size,3))
Enarr = np.concatenate((Ensarr.reshape((-1,1)),nsarr), axis=1)
# Ensarr.sort()
# Enarren = Enarr[:,0]
sorted_indices = np.argsort(Ensarr)
Enarr = Enarr[sorted_indices]

In [47]:
display(Ens[1], Ensarr, Ensarr.shape, nsarr.shape, nsarr, Enarr)

5*hbar/2

array([3/2, 5/2, 7/2, ..., 59/2, 61/2, 63/2], dtype=object)

(1331,)

(1331, 3)

array([[ 0,  0,  0],
       [ 0,  0,  1],
       [ 0,  0,  2],
       ...,
       [10, 10,  8],
       [10, 10,  9],
       [10, 10, 10]])

array([[3/2, 0, 0, 0],
       [5/2, 0, 0, 1],
       [5/2, 0, 1, 0],
       ...,
       [61/2, 10, 10, 9],
       [61/2, 9, 10, 10],
       [63/2, 10, 10, 10]], dtype=object)

In [73]:
E_val = 5.5   # INPUT
matching_indices = np.where(Enarr[:,0]==E_val)[0]
if matching_indices.size > 0:
    Enrows = Enarr[matching_indices]
    # display(Enrows)
    for i in range(matching_indices.size):
        print(f'E = {Enrows[i][0]};\t n1={Enrows[i][1]}, n2={Enrows[i][2]}, n3={Enrows[i][3]}')
else:
    print(f'None of the states has energy = {E_val}.')

E = 11/2;	 n1=1, n2=1, n3=2
E = 11/2;	 n1=1, n2=2, n3=1
E = 11/2;	 n1=2, n2=1, n3=1
E = 11/2;	 n1=0, n2=4, n3=0
E = 11/2;	 n1=1, n2=3, n3=0
E = 11/2;	 n1=2, n2=2, n3=0
E = 11/2;	 n1=2, n2=0, n3=2
E = 11/2;	 n1=0, n2=3, n3=1
E = 11/2;	 n1=3, n2=0, n3=1
E = 11/2;	 n1=4, n2=0, n3=0
E = 11/2;	 n1=0, n2=2, n3=2
E = 11/2;	 n1=0, n2=0, n3=4
E = 11/2;	 n1=3, n2=1, n3=0
E = 11/2;	 n1=0, n2=1, n3=3
E = 11/2;	 n1=1, n2=0, n3=3
