# CC 11 - Quantum Mechanics - DB sir

## Description:
* [L-S Coupling](#l-s-coupling) : Get the results of LS coupling.

* [J-J Coupling](#j-j-coupling) : Get the results of JJ coupling.

* [Anamolous Zeemann Effect](#anamolous-zeemann-effect) : Get energy levels.


In [23]:
# notes

## Modules to import

In [24]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [25]:
import sympy as sp
sp.init_printing(use_unicode=True)

## Linear Harmonic Oscillator

## Hydrogen Atom Problem

## Vector Atom Model

### L-S Coupling

In [26]:
L_LS_coupling = lambda l1,l2: np.arange(np.abs(l1-l2), l1+l2+1)
S_LS_coupling = lambda s1,s2: np.arange(np.abs(s1-s2), s1+s2+1)

def J_LS_coupling(l1,s1, l2,s2, print_TrueFalse=False, show_table=False):
    L, S = L_LS_coupling(l1,l2), S_LS_coupling(s1,s2)
    Ls_list, Ss_list = [], []
    Js_list = []
    if print_TrueFalse == True:
        print(f'l1={l1}, s1={s1}, \t l2={l2}, s2={s2}')
        print(f'L = {L}, \t S = {S} \n')
    else:
        print(end='')
    for l in L:
        for s in S:
            Ls_list.append(l), Ss_list.append(s)
            J_elt = np.arange(np.abs(l-s), l+s+1)
            Js_list.append(J_elt)
            if print_TrueFalse == True:
                print(f'L={l}, S={s}, \t J = {J_elt}')
            else:
                print(end='')
    dict_ls_js = {'L':Ls_list,'S':Ss_list,'J':Js_list}
    df_ls_js = pd.DataFrame(dict_ls_js)
    if show_table == True:
        display(df_ls_js)
    else:
        print(end='')
    return Js_list, df_ls_js

J_LS_coupling(1,1/2, 2,1/2, print_TrueFalse=True, show_table=True)

l1=1, s1=0.5, 	 l2=2, s2=0.5
L = [1 2 3], 	 S = [0. 1.] 

L=1, S=0.0, 	 J = [1.]
L=1, S=1.0, 	 J = [0. 1. 2.]
L=2, S=0.0, 	 J = [2.]
L=2, S=1.0, 	 J = [1. 2. 3.]
L=3, S=0.0, 	 J = [3.]
L=3, S=1.0, 	 J = [2. 3. 4.]


L    S                J
0  1  0.0            [1.0]
1  1  1.0  [0.0, 1.0, 2.0]
2  2  0.0            [2.0]
3  2  1.0  [1.0, 2.0, 3.0]
4  3  0.0            [3.0]
5  3  1.0  [2.0, 3.0, 4.0]

([array([1.]),
  array([0., 1., 2.]),
  array([2.]),
  array([1., 2., 3.]),
  array([3.]),
  array([2., 3., 4.])],
    L    S                J
 0  1  0.0            [1.0]
 1  1  1.0  [0.0, 1.0, 2.0]
 2  2  0.0            [2.0]
 3  2  1.0  [1.0, 2.0, 3.0]
 4  3  0.0            [3.0]
 5  3  1.0  [2.0, 3.0, 4.0])

### J-J Coupling

In [27]:
J1_JJ_coupling = lambda l1,s1: np.arange(np.abs(l1-s1), l1+s1+1)
J2_JJ_coupling = lambda l2,s2: np.arange(np.abs(l2-s2), l2+s2+1)

def J_JJ_coupling(l1,s1, l2,s2, print_TrueFalse=False, show_table=False):
    J1, J2 = J1_JJ_coupling(l1,s1), J2_JJ_coupling(l2,s2)
    J1_list, J2_list = [], []
    Js_list = []
    if print_TrueFalse == True:
        print(f'l1={l1}, s1={s1}, \t l2={l2}, s2={s2}')
        print(f'J1 = {J1}, \t J2 = {J2} \n')
    else:
        print(end='')
    for j1 in J1:
        for j2 in J2:
            J1_list.append(j1), J2_list.append(j2)
            J_elt = np.arange(np.abs(j1-j2), j1+j2+1)
            Js_list.append(J_elt)
            if print_TrueFalse == True:
                print(f'J1={j1}, J2={j2}, \t J = {J_elt}')
            else:
                print(end='')
    dict_jj_js = {'J1':J1_list,'J2':J2_list,'J':Js_list}
    df_jj_js = pd.DataFrame(dict_jj_js)
    if show_table == True:
        display(df_jj_js)
    else:
        print(end='')
    return Js_list, df_jj_js

J_JJ_coupling(1,1/2, 2,1/2, print_TrueFalse=True, show_table=True)

l1=1, s1=0.5, 	 l2=2, s2=0.5
J1 = [0.5 1.5], 	 J2 = [1.5 2.5] 

J1=0.5, J2=1.5, 	 J = [1. 2.]
J1=0.5, J2=2.5, 	 J = [2. 3.]
J1=1.5, J2=1.5, 	 J = [0. 1. 2. 3.]
J1=1.5, J2=2.5, 	 J = [1. 2. 3. 4.]


J1   J2                     J
0  0.5  1.5            [1.0, 2.0]
1  0.5  2.5            [2.0, 3.0]
2  1.5  1.5  [0.0, 1.0, 2.0, 3.0]
3  1.5  2.5  [1.0, 2.0, 3.0, 4.0]

([array([1., 2.]),
  array([2., 3.]),
  array([0., 1., 2., 3.]),
  array([1., 2., 3., 4.])],
     J1   J2                     J
 0  0.5  1.5            [1.0, 2.0]
 1  0.5  2.5            [2.0, 3.0]
 2  1.5  1.5  [0.0, 1.0, 2.0, 3.0]
 3  1.5  2.5  [1.0, 2.0, 3.0, 4.0])

### Selection Rules

In [69]:
def selection_rule(S1,L1,J1, S2,L2,J2):
    dS, dL, dJ = (S2-S1), (L2-L1), (J2-J1)
    trans12 = []
    if np.abs(dS)==0 and np.abs(dL)==1 and (np.abs(dJ)==1 or np.abs(dJ)==0):
        # print('Transition is possible.')
        if dL==-1 and dJ==-1:
            trans12.append('Possible Transition. Strongest Intensity. 4/4')
        elif dL==1 and dJ==1:
            trans12.append('Possible Transition. Less Intensity. 3/4')
        elif dL==-1 and dJ==0:
            trans12.append('Possible Transition. Weak Intensity. 2/4')
        elif dL==1 and dJ==0:
            trans12.append('Possible Transition. Very Weak Intensity. 1/4')
        elif dL==-1 and dJ==1:
            trans12.append('Forbidden transition.')
        elif dL==1 and dJ==-1:
            trans12.append('Forbidden transition.')
    else:
        trans12.append('Forbidden transition.')
    if trans12[0] == 'Forbidden transition.':
        trans12.append(False)
    else:
        trans12.append(True)
    return trans12

selection_rule(1/2,1,3/2, 1/2,2,3/2)

['Possible Transition. Very Weak Intensity. 1/4', True]

### Anamolous Zeemann Effect
(Selection Rules will also be applied here)

In [70]:
g_J = lambda L,S,J: 1 + (J*(J+1)+S*(S+1)-L*(L+1))/(2*J*(J+1))
mu_J = lambda L,S,J: -1*g_J(L,S,J)* np.sqrt(J*(J+1)) # e hbar/ 2me = 1
E_B = lambda L,S,J,mj: g_J(L,S,J)* 1*mj         # muB B = 1

In [71]:
# nP1b2 - n:2s+1, P:L=1, 1b2:J=1/2
def orbital_nL_J(L,J):
    mjs = []
    Ejs = []
    for mjelt in np.arange(-J,J+1):
        mjs.append(mjelt)
        Ejelt = E_B(L, 1/2, J, mjelt)
        Ejs.append(Ejelt)
    return [L,J, np.array(mjs), np.array(Ejs)]

display(orbital_nL_J(0,1/2))

[0, 0.5, array([-0.5,  0.5]), array([-1.,  1.])]

In [72]:
def two_orbital_interaction(L1,J1, L2,J2, print_TrueFalse=False, show_table=False):
    trans12, transTF = selection_rule(1/2,L1,J1, 1/2,L2,J2)
    
    l1, j1, mjs1, Ejs1 = orbital_nL_J(L1,J1)
    l2, j2, mjs2, Ejs2 = orbital_nL_J(L2,J2)
    if print_TrueFalse == True:
        print(f'\nL1 = {l1}, J1 = {j1}, \t mjs1 = {mjs1}, \t Ejs1 = {Ejs1}')
        print(f'L2 = {l2}, J2 = {j2}, \t mjs2 = {mjs2}, \t Ejs2 = {Ejs2}\n')
    else:
        print(end='')
    if print_TrueFalse==True or show_table==True:
        print(f'{trans12}\n')
    else:
        print(end='')
    if transTF == True:
        mj1s, mj2s = [], []
        pi_sig = []
        E12s = []
        for mj1 in mjs1:
            for mj2 in mjs2:
                E1, E2 = Ejs1[int(mj1+J1)], Ejs2[int(mj2+J2)]
                E12 = (E2-E1)
                if (mj1-mj2)==0:
                    mj1s.append(mj1), mj2s.append(mj2)
                    pi_sig.append('pi')
                    E12s.append(E12)
                    if print_TrueFalse == True:
                        print(f'pi, \t mj1={mj1}, mj2={mj2},\t E2-E1={E12}')
                    else:
                        print(end='')
                elif (mj1-mj2)==1:
                    mj1s.append(mj1), mj2s.append(mj2)
                    pi_sig.append('sigma-')
                    E12s.append(E12)
                    if print_TrueFalse == True:
                        print(f'sigma-,\t mj1={mj1}, mj2={mj2},\t E2-E1={E12}')
                    else:
                        print(end='')
                elif (mj1-mj2)==-1:
                    mj1s.append(mj1), mj2s.append(mj2)
                    pi_sig.append('sigma+')
                    E12s.append(E12)
                    if print_TrueFalse == True:
                        print(f'sigma+,\t mj1={mj1}, mj2={mj2},\t E2-E1={E12}')
                    else:
                        print(end='')
        mj1s, mj2s = np.array(mj1s), np.array(mj2s)
        pi_sig, E12s = np.array(pi_sig), np.array(E12s)
        dict_en_lvl = {'mj1':mj1s,'mj2':mj2s,'pi/sigma':pi_sig,'E2-E1':E12s}
        df_en_lvl = pd.DataFrame(dict_en_lvl)
        if show_table == True:
            display(df_en_lvl)
        else:
            print(end='')
        return trans12, pi_sig, E12s, df_en_lvl
    
    elif transTF == False:
        return trans12


Verifying the 4+6=10 lines

In [73]:
display(two_orbital_interaction(0,1/2, 1,1/2, print_TrueFalse=True),
        two_orbital_interaction(0,1/2, 1,3/2, print_TrueFalse=True),
        two_orbital_interaction(1,1/2, 1,3/2))


L1 = 0, J1 = 0.5, 	 mjs1 = [-0.5  0.5], 	 Ejs1 = [-1.  1.]
L2 = 1, J2 = 0.5, 	 mjs2 = [-0.5  0.5], 	 Ejs2 = [-0.33333333  0.33333333]

Possible Transition. Very Weak Intensity. 1/4

pi, 	 mj1=-0.5, mj2=-0.5,	 E2-E1=0.6666666666666666
sigma+,	 mj1=-0.5, mj2=0.5,	 E2-E1=1.3333333333333335
sigma-,	 mj1=0.5, mj2=-0.5,	 E2-E1=-1.3333333333333335
pi, 	 mj1=0.5, mj2=0.5,	 E2-E1=-0.6666666666666666

L1 = 0, J1 = 0.5, 	 mjs1 = [-0.5  0.5], 	 Ejs1 = [-1.  1.]
L2 = 1, J2 = 1.5, 	 mjs2 = [-1.5 -0.5  0.5  1.5], 	 Ejs2 = [-2.         -0.66666667  0.66666667  2.        ]

Possible Transition. Less Intensity. 3/4

sigma-,	 mj1=-0.5, mj2=-1.5,	 E2-E1=-1.0
pi, 	 mj1=-0.5, mj2=-0.5,	 E2-E1=0.33333333333333337
sigma+,	 mj1=-0.5, mj2=0.5,	 E2-E1=1.6666666666666665
sigma-,	 mj1=0.5, mj2=-0.5,	 E2-E1=-1.6666666666666665
pi, 	 mj1=0.5, mj2=0.5,	 E2-E1=-0.33333333333333337
sigma+,	 mj1=0.5, mj2=1.5,	 E2-E1=1.0


('Possible Transition. Very Weak Intensity. 1/4',
 array(['pi', 'sigma+', 'sigma-', 'pi'], dtype='<U6'),
 array([ 0.66666667,  1.33333333, -1.33333333, -0.66666667]),
    mj1  mj2 pi/sigma     E2-E1
 0 -0.5 -0.5       pi  0.666667
 1 -0.5  0.5   sigma+  1.333333
 2  0.5 -0.5   sigma- -1.333333
 3  0.5  0.5       pi -0.666667)

('Possible Transition. Less Intensity. 3/4',
 array(['sigma-', 'pi', 'sigma+', 'sigma-', 'pi', 'sigma+'], dtype='<U6'),
 array([-1.        ,  0.33333333,  1.66666667, -1.66666667, -0.33333333,
         1.        ]),
    mj1  mj2 pi/sigma     E2-E1
 0 -0.5 -1.5   sigma- -1.000000
 1 -0.5 -0.5       pi  0.333333
 2 -0.5  0.5   sigma+  1.666667
 3  0.5 -0.5   sigma- -1.666667
 4  0.5  0.5       pi -0.333333
 5  0.5  1.5   sigma+  1.000000)

'Forbidden transition.'

In [74]:
# rearrange energies

Transitions between 2 arbitary orbitals

In [77]:
two_orbital_interaction(1,3/2, 2,3/2, show_table=True)

Possible Transition. Very Weak Intensity. 1/4



mj1  mj2 pi/sigma     E2-E1
0 -1.5 -1.5       pi  0.800000
1 -1.5 -0.5   sigma+  1.600000
2 -0.5 -1.5   sigma- -0.533333
3 -0.5 -0.5       pi  0.266667
4 -0.5  0.5   sigma+  1.066667
5  0.5 -0.5   sigma- -1.066667
6  0.5  0.5       pi -0.266667
7  0.5  1.5   sigma+  0.533333
8  1.5  0.5   sigma- -1.600000
9  1.5  1.5       pi -0.800000

('Possible Transition. Very Weak Intensity. 1/4',
 array(['pi', 'sigma+', 'sigma-', 'pi', 'sigma+', 'sigma-', 'pi', 'sigma+',
        'sigma-', 'pi'], dtype='<U6'),
 array([ 0.8       ,  1.6       , -0.53333333,  0.26666667,  1.06666667,
        -1.06666667, -0.26666667,  0.53333333, -1.6       , -0.8       ]),
    mj1  mj2 pi/sigma     E2-E1
 0 -1.5 -1.5       pi  0.800000
 1 -1.5 -0.5   sigma+  1.600000
 2 -0.5 -1.5   sigma- -0.533333
 3 -0.5 -0.5       pi  0.266667
 4 -0.5  0.5   sigma+  1.066667
 5  0.5 -0.5   sigma- -1.066667
 6  0.5  0.5       pi -0.266667
 7  0.5  1.5   sigma+  0.533333
 8  1.5  0.5   sigma- -1.600000
 9  1.5  1.5       pi -0.800000)