# Quantum Mechanics in QuTip

In [36]:
import numpy as np
import matplotlib.pyplot as plt
# from scipy.linalg import eigh, eigh_tridiagonal
from scipy.integrate import simps
%matplotlib inline

In [37]:
import qutip as qp

## Schrodinger equation

In 1D:
$$ -\frac{\hbar^2}{2m} \frac{d^2\psi}{dx^2} + V(x)\psi(x) = E \psi(x) $$

In [38]:
hcut = 1
mass = 1  # INPUT

Potential

In [39]:
L = 10
x_min, x_max = -L, L
N = 100  # INPUT no. of grid points
x = np.linspace(x_min, x_max, N) # x axis

# potential
def potential1d(x, omega):
    return 0.5*mass*(omega**2)* x**2

omega1 = 1 # INPUT
Vx = potential1d(x=x, omega=omega1)

Solution

In [40]:
dx = x[1] - x[0]
T = (-hcut**2/(2*mass)) * (np.diag(-2/dx**2 * np.ones(N))
                        + np.diag(1/dx**2 * np.ones(N-1), 1)
                        + np.diag(1/dx**2 * np.ones(N-1), -1))
H = T + np.diag(Vx*np.ones(N))

H_oper =  qp.Qobj(H)
display(H_oper)
H_states = H_oper.eigenstates()
H_values = H_oper.eigenenergies()

def H_eigenvalue(n):
    # return H_values[n] # alternative
    return np.array(H_states)[:,n][0]
def H_eigenket(n):
    return np.array(H_states)[:,n][1]
def H_eigenket_arr(n):
    return np.array(H_eigenket(n)).T[0]

Quantum object: dims = [[100], [100]], shape = (100, 100), type = oper, isherm = True
Qobj data =
[[ 74.5025     -12.25125      0.         ...   0.           0.
    0.        ]
 [-12.25125     72.50270406 -12.25125    ...   0.           0.
    0.        ]
 [  0.         -12.25125     70.54372028 ...   0.           0.
    0.        ]
 ...
 [  0.           0.           0.         ...  70.54372028 -12.25125
    0.        ]
 [  0.           0.           0.         ... -12.25125     72.50270406
  -12.25125   ]
 [  0.           0.           0.         ...   0.         -12.25125
   74.5025    ]]

In [45]:
display(H_eigenket(5))

Quantum object: dims = [[100], [1]], shape = (100, 1), type = ket
Qobj data =
[[ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 1.98156673e-12]
 [ 8.60702929e-12]
 [ 3.61144026e-11]
 [ 1.46308021e-10]
 [ 5.71987622e-10]
 [ 2.15673969e-09]
 [ 7.83887925e-09]
 [ 2.74471752e-08]
 [ 9.25251170e-08]
 [ 3.00094477e-07]
 [ 9.35828610e-07]
 [ 2.80389445e-06]
 [ 8.06532968e-06]
 [ 2.22548036e-05]
 [ 5.88554696e-05]
 [ 1.49039361e-04]
 [ 3.61010030e-04]
 [ 8.35507519e-04]
 [ 1.84522111e-03]
 [ 3.88328819e-03]
 [ 7.77506627e-03]
 [ 1.47826005e-02]
 [ 2.66306837e-02]
 [ 4.53359687e-02]
 [ 7.26944039e-02]
 [ 1.09326695e-01]
 [ 1.53350609e-01]
 [ 1.99058144e-01]
 [ 2.36341270e-01]
 [ 2.51812385e-01]
 [ 2.32299701e-01]
 [ 1.70454002e-01]
 [ 7.07317774e-02]
 [-4.72996213e-02]
 [-1.51511668e-01]
 [-2.06914592e-01]
 [-1.90146175e-01]
 [-1.02621212e-01]
 [ 2.51419584e-02]
 [ 1.42628089e-01]
 [ 1.99912961e-01]
 [ 1.70819

In [41]:
display(H_eigenket(14).dag()*H_oper*H_eigenket(14), H_eigenvalue(14))

Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[13.94104418]]

13.941044180552927

## Angular Momentum

In [42]:
display('sigma_x', qp.sigmax(), qp.sigmax().eigenstates())
display('sigma_y', qp.sigmay(), qp.sigmay().eigenstates())
display('sigma_z', qp.sigmaz(), qp.sigmaz().eigenstates())

'sigma_x'

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]

(array([-1.,  1.]),
 array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[-0.70710678]
         [ 0.70710678]]                                              ,
        Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[0.70710678]
         [0.70710678]]                                               ],
       dtype=object))

'sigma_y'

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.-1.j]
 [0.+1.j 0.+0.j]]

(array([-1.,  1.]),
 array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[-0.70710678+0.j        ]
         [ 0.        +0.70710678j]]                                  ,
        Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[-0.70710678+0.j        ]
         [ 0.        -0.70710678j]]                                  ],
       dtype=object))

'sigma_z'

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]

(array([-1.,  1.]),
 array([Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[ 0.]
         [-1.]]                                                      ,
        Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
        Qobj data =
        [[-1.]
         [ 0.]]                                                      ],
       dtype=object))

In [49]:
sigx = qp.jmat(1, 'x')  # INPUT
display('sigma_x', sigx)

sigx_eigv = sigx.eigenstates()

def sigx_eigenvalue(n):
    return np.array(sigx_eigv)[:,n][0]
def sigx_eigenket(n):
    return np.array(sigx_eigv)[:,n][1]

for i in range(3):  # INPUT
    display(sigx_eigenvalue(i), sigx_eigenket(i))


'sigma_x'

Quantum object: dims = [[3], [3]], shape = (3, 3), type = oper, isherm = True
Qobj data =
[[0.         0.70710678 0.        ]
 [0.70710678 0.         0.70710678]
 [0.         0.70710678 0.        ]]

-0.9999999999999984

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[ 0.5       ]
 [-0.70710678]
 [ 0.5       ]]

1.3322676295501878e-15

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[-0.70710678]
 [ 0.        ]
 [ 0.70710678]]

1.0

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[0.5       ]
 [0.70710678]
 [0.5       ]]