# CC 01 (Mathematical Physics 1) All Codes

## Content

> **Calculation of mean, variance, std dev**

> **GCD and LCD of 2 numbers**

> **Pythagoras number generation**

> **Sorting ascending order**

> **Binary and Decimal conversions** (binary to decimal and decimal to binary)

> **Roots of quadratic equation**

> **Bisection Method**

> **Newton - Raphson method**

> **Secant method**

> **Interpolation** (direct forward difference method)

> **Matrices** (addition and multiplication)

> **Integration** (trapezoidal and Simpson's method)

### Calculation of mean, variance, std dev

In [1]:
import math
import numpy as np

x = [2, 3, 0, 1, -2, 5]
y = [i**2 for i in x]
n = len(x)
meanfn = np.sum(x)/n
varfn = np.sum(y)/n - meanfn**2
stdevfn = math.sqrt(varfn)
print(f'mean, var, stdev = {meanfn}, {varfn}, {stdevfn}')

mean, var, stdev = 1.5, 4.916666666666667, 2.217355782608345


### GCD and LCD of 2 numbers

In [2]:
# m1, n1 = eval(input('enter 2 numbers: m, n = '))
m1, n1 = 20, 135       # INPUT
mnprod = m1*n1

def gcd(m, n):
    r = m % n
    while r > 0:
        m, n = n, r
        r = m % n
    return n

print(f'numbers: {m1}, {n1} \nGCD = {gcd(m1,n1)} and LCD = {mnprod/gcd(m1,n1)}')

numbers: 20, 135 
GCD = 5 and LCD = 540.0


### Pythagoras number generation

In [3]:
def gcd(m, n):
    r = m % n
    while r > 0:
        m, n = n, r
        r = m % n
    return n

# n1 = eval(input('enter a number: '))
n1 = 4      # INPUT

for m in range(1, n1):
    if gcd(m, n1) == 1:
        x = n**2 - m**2
        y = 2*n*m
        z = n**2 + m**2
        print(f'x = {x}, y = {y}, z = {z}')

x = 35, y = 12, z = 37
x = 27, y = 36, z = 45


### Sorting ascending order

In [4]:
L = [10, -2, 0, 1, 100, 15, 9, -12]

def sort_ascending(L):
    n = len(L)
    for i in range(n):
        key = L[i]
        j = i-1
        while j >= 0 and L[j] > key:
            L[j+1] = L[j]
            j = j-1
        L[j+1] = key
    return L

print(f'''Original form: {L}
sort by defined function: {sort_ascending(L)} 
sort by available function (sorted): {sorted(L)}''')

L.sort()
print(f'sort: {L}')
L.sort(reverse=True)
print(f'sort(reverse): {L}')

Original form: [10, -2, 0, 1, 100, 15, 9, -12]
sort by defined function: [-12, -2, 0, 1, 9, 10, 15, 100] 
sort by available function (sorted): [-12, -2, 0, 1, 9, 10, 15, 100]
sort: [-12, -2, 0, 1, 9, 10, 15, 100]
sort(reverse): [100, 15, 10, 9, 1, 0, -2, -12]


## Binary and Decimal conversions

### Decimal to Binary conversion

In [5]:
from math import modf

# n = eval(input('enter the decimal number: '))
n = 106.125    # INPUT

ndec, nint = modf(n)
nint = int(nint)
print(f'integer part = {nint}, decimal part = {ndec}')

def bin_int(n):
    b = str()
    while n > 0:
        res = n % 2
        b += str(res)
        n = n//2
    return b[::-1]

def bin_frac(n):
    b = str()
    i = 1
    while n>0:
        n = n*2
        frac, intg = modf(n)
        b += str(int(intg))
        n = frac
        i += 1
        if i>6:  # input
            break
    return b

print(f'the binary number is {bin_int(nint)}.{bin_frac(ndec)}')

integer part = 106, decimal part = 0.125
the binary number is 1101010.001


### Binary to Decimal conversion

In [6]:
# m = eval(input('give the binary number: '))
m = 1101010     # INPUT - binary no.

s, i = 0, 0
while m > 0:
    res = m % 10
    m = m//10
    s += (2**i)*res
    i += 1
print(f'Decimal number for the given binary number is {s}.')

Decimal number for the given binary number is 106.


## Numerical methods for finding roots

### Roots of quadratic equation
$$ ax^2 +bx +c =0 $$

In [7]:
import math as m
# a, b, c = eval(input('a, b, c = '))
a, b, c = 5, 3, 4    # INPUT
D = b**2 -4*a*c
D1 = m.sqrt(abs(D))
a2 = 2*a

if D > 0:
    print(f'distinct real roots = {(-b +D1)/a2}, {(-b -D1)/a2}')
elif D == 0:
    print(f'equal real roots = {-b/a2}, {-b/a2}')
elif D < 0:
    print(f'complex roots: {complex(-b,D1)/a2}, {complex(-b,-D1)/a2}')


complex roots: (-0.3+0.8426149773176359j), (-0.3-0.8426149773176359j)


In [8]:
a, b, c = 4, 8, 7   # INPUT
D1 = (b**2 - 4*a*c)**0.5
print(f'D = {D1**2} \nroots = {(-b +D1)/(2*a)}, {(-b -D1)/(2*a)}')

D = (-47.99999999999999+5.878304635907294e-15j) 
roots = (-1+0.8660254037844386j), (-1-0.8660254037844386j)


### Bisection method
Here in this code we need to change $a$ and $b$ again and again to get root at that interval. The code gives only one root at a time.

In [9]:
def f(x):
    return x**3 -2*x -5     # INPUT

# a, b, tol = eval(input('lower input, upper limit, tol = '))
a, b, tol = -5, 15, 1e-4  # INPUT - lower input, upper limit, tol

while f(a)*f(b) > 0:
    # print('no root exists in this interval')
    break
while abs(b-a) >= tol:
    xm = (a+b)/2
    if f(xm) == 0:
        print(f'root = {xm}')
        break
    if f(a)*f(xm) < 0:
        b = xm
    else:
        a = xm
print(f'root = {(a+b)/2}')

root = 2.0945358276367188


### Newton - Raphson method

In [10]:
def f(x):
    return x**3 -2*x -5
def h(x):
    return 3*x**2 -2

# x1, tol = eval(input('initial point, tol = '))
x1, tol = -6, 1e-3      # INPUT - initial point, tol

while abs(f(x1)) >= tol:
    x1 = x1 - f(x1)/h(x1)
    print(x1)
print(f'\nroot = {x1} ; tolerance={tol}')

-4.028301886792453
-2.693483521794348
-1.7243822197186387
-0.759322893194342
-15.259351046905664
-10.194932062770665
-6.824358520491854
-4.579337634778419
-3.0710458423450495
-2.012935001523651
-1.113899354424766
1.2981422326618364
3.0682796565942985
2.3919371989751514
2.134667045516952
2.095429011690451
2.09455191476237

root = 2.09455191476237 ; tolerance=0.001


### Secant method

In [11]:
def f(x):
    return x**3 -2*x -5
# x0, x1, tol = eval(input('x0, x1, tol = '))
x0, x1, tol = -2, 10, 1e-3   # INPUT

while abs(f(x1))>=tol:
    x2 = x1 - f(x1)*(x1-x0)/(f(x1)-f(x0))
    x0, x1 = x1, x2
    print(f'x1={x1}, f(x1)={f(x1)}')
print(f'\n\t root = {x1}')

x1=-1.8902439024390247, f(x1)=-7.973395264143007
x1=-1.7937961095710024, f(x1)=-7.18431356369607
x1=-0.9156726071531723, f(x1)=-3.936406273408437
x1=0.14859756893267784, f(x1)=-5.293913919654915
x1=-4.001769255912077, f(x1)=-61.081423340691565
x1=0.5424435200020472, f(x1)=-5.925275761436758
x1=1.030616008431287, f(x1)=-5.966543274043425
x1=-69.55038326749722, f(x1)=-336298.89496660174
x1=1.031868263685297, f(x1)=-5.965052612653974
x1=1.0331202282865473, f(x1)=-5.963552591929615
x1=6.010489288290772, f(x1)=200.11384616594682
x1=1.1771573829560573, f(x1)=-5.723128363928088
x1=1.3115442149762924, f(x1)=-5.367037972830224
x1=3.337039000941287, f(x1)=25.48661865936325
x1=1.6638819478951445, f(x1)=-3.721301504224705
x1=1.877054327969876, f(x1)=-2.1406212929809927
x1=2.165741016534392, f(x1)=0.8267835924546123
x1=2.085306621269804, f(x1)=-0.10264967448805518
x1=2.0941900610876116, f(x1)=-0.004033151144833269
x1=2.0945533699354257, f(x1)=2.1077204387154325e-05

	 root = 2.0945533699354257


## Interpolation

### Direct forward difference method

In [12]:
x = list(range(10))
y = [0, 0.368, 0.541, 0.448, 0.39, 0.34, 0.38, 0.31, 0.2, 0.14]

xx = 4.7  # input value
n = len(x)
h = x[1] - x[0]
p = (xx - x[0])/h
cf = p
k = 1
yy = y[0]
d = []
for i in range(n, 1, -1):
    for j in range(i-1):
        diff = y[j+1] - y[j]
        d.append(diff)
    yy += cf*d[0]
    cf *= (p-k)/(k+1)
    k += 1
    y = d
    d = []
print(f'for x = {xx}, y = {yy}')

for x = 4.7, y = 0.3468285114337938


## Matrices

### Matrix addition

In [13]:
A = [[1,2,3], [4,5,6]]
B = [[15,6,4], [3,4,2]]
C = [[0,0,0], [0,0,0]] # null matrix with the dimension of the result

row = len(A)
col = len(A[0])

for i in range(row):
    for j in range(col):
        C[i][j] = A[i][j] + B[i][j]

print(f'using defined function: {C}')
for rows in C:
    print(rows)

# using numpy arrays
import numpy as np
An = np.array(A)
Bn = (B)
Cn = An + Bn
print(f'using numpy array: \n{Cn}')

using defined function: [[16, 8, 7], [7, 9, 8]]
[16, 8, 7]
[7, 9, 8]
using numpy array: 
[[16  8  7]
 [ 7  9  8]]


### Matrix multiplication

In [14]:
A = [[1,2,3], [4,5,6]]
B = [[1,2], [3,4], [5,6]]
C = [[0,0], [0,0]] # null matrix with the dimension of the result

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[i][j] = A[i][k]*B[k][j]

print(f'multiplication by defined function: {C}')
for rows in C:
    print(rows)

# using numpy arrays
import numpy as np
A_arr = np.array(A)
B_arr = np.array(B)
AB = A_arr.dot(B_arr)
print(f'multiplication using numpy arrays: \n{AB}')

multiplication by defined function: [[15, 18], [30, 36]]
[15, 18]
[30, 36]
multiplication using numpy arrays: 
[[22 28]
 [49 64]]


## Integration

### Integration by trapizoidal rule

In [15]:
import numpy as np

def f(x):
    return x**2

a, b, n = 0, 1, 400
h = (b -a)/n
sumtn = f(a) + f(b)
for i in range(1, n-1):
    sumtn = sumtn + 2*f(a + i*h)
intg = sumtn*0.5*h
print('value=', intg)

value= 0.3308468593750001


### Integration by Simpson's rule
$$ I = \int_a^b f(x)dx $$
For Simpson's rule, we divide the interval [a,b] into an even number of sub-intervals.
$$ I = \frac{h}{3} [y_0 + 4(y_1+y_3+...+y_{n-1}) + 2(y_2+y_4+...+y_{n-2}) + y_n] $$

In [16]:
import numpy as np

def f(x):
    return np.sin(x)  # INPUT

a, b = np.pi/3, np.pi  # INPUT
n = 400     # INPUT

h = (b-a)/n
sm = f(a) + f(b)
sm_odd = 0
sm_even = 0
for i in range(1, n-1, 2):
    sm_odd += 4 *f(a + i*h)
    sm_even += 2 *f(a + (i+1)*h)
intg = h/3 * (sm + sm_odd + sm_even)
print('value=', intg)

value= 1.499963446082914


In [17]:
import numpy as np

def f1(x):
    return np.sin(x)  # INPUT

a, b = np.pi/3, np.pi  # INPUT
n = 400     # INPUT

h = float(b-a)/n
x0 = np.arange(a+ h, b, 2*h)
xe = np.arange(a+ 2*h, b, 2*h)
val = h/3*(f1(a) + 4*sum(f1(x0)) + 2*sum(f1(xe)) + f1(b))
print('value of the integration is ', val)

value of the integration is  1.500000000006262
