## Solution of a Matrix Equation in Python

In python, a matrix equation can be solved using different functions. Here I will consider a matrix equation,
$$ AX = B $$
where, 
$A= \begin{bmatrix}  2 & 1 & 0 & 0\\ 2 & 6 & 4 & 0 \\ 0 & 4 & 9 & 4 \\ 0 & 0 & 3 & 1 \end{bmatrix}$, 
$B = \begin{bmatrix} 0\\ 4\\ 8\\ 7 \end{bmatrix}$ and $X$ is to be calculated.

(As throughout the project, I am dealing with tridiagonal matrices, here I am testing speed for tridiagonal matrix only.)

Let's write the matrices $A$ and $B$ as a *list*.

In [1]:
al, bt = -2, 5 -1j
N = 12
A = [[0 for j in range(N)] for i in range(N)]
B = [2,8,3,4,3,8,3,0,6,2,3,5]
A[0][0], A[N-1][N-1] = 1, 1
for j in range(1, N-1):
    A[j][j-1], A[j][j], A[j][j+1] = al, bt, al
display(A, B)

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [-2, (5-1j), -2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, -2, (5-1j), -2, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, -2, (5-1j), -2, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, -2, (5-1j), -2, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, -2, (5-1j), -2, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, -2, (5-1j), -2, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, -2, (5-1j), -2, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, -2, (5-1j), -2, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, -2, (5-1j), -2, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, -2, (5-1j), -2],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]

[2, 8, 3, 4, 3, 8, 3, 0, 6, 2, 3, 5]

In most of the cases, the process of finding $X$ is by the equation,
$$X = A^{-1} B$$
Now, in python we have different ways available for finding inverse of a matrix.

Here the matrix equation is solved using different methods and the speed of computation is also checked.

## Using numpy.linalg

In [2]:
import numpy as np
import numpy.linalg as npLA

Aarr, Barr = np.array(A), np.array(B)
npLA.inv(A) @ B

array([2.        +4.30252080e-16j, 3.07246374+1.33729704e+00j,
       2.34980786+1.80701073e+00j, 2.20556128+2.00532585e+00j,
       2.16675826+2.10352326e+00j, 2.76309599+2.17010316e+00j,
       1.82603331+1.94018666e+00j, 1.2720806 +1.76734683e+00j,
       2.23784162+1.84214011e+00j, 2.2435935 +1.71908264e+00j,
       3.23068345+1.33376975e+00j, 5.        +0.00000000e+00j])

In [3]:
npLA.solve(Aarr, Barr)

array([2.        +4.44089210e-16j, 3.07246374+1.33729704e+00j,
       2.34980786+1.80701073e+00j, 2.20556128+2.00532585e+00j,
       2.16675826+2.10352326e+00j, 2.76309599+2.17010316e+00j,
       1.82603331+1.94018666e+00j, 1.2720806 +1.76734683e+00j,
       2.23784162+1.84214011e+00j, 2.2435935 +1.71908264e+00j,
       3.23068345+1.33376975e+00j, 5.        +0.00000000e+00j])

## Using scipy.linalg

In [4]:
import scipy.linalg as spLA

spLA.inv(A) @ B

array([2.        +3.11352320e-17j, 3.07246374+1.33729704e+00j,
       2.34980786+1.80701073e+00j, 2.20556128+2.00532585e+00j,
       2.16675826+2.10352326e+00j, 2.76309599+2.17010316e+00j,
       1.82603331+1.94018666e+00j, 1.2720806 +1.76734683e+00j,
       2.23784162+1.84214011e+00j, 2.2435935 +1.71908264e+00j,
       3.23068345+1.33376975e+00j, 5.        +0.00000000e+00j])

## By LU factorization

In [5]:
lu1, piv1 = spLA.lu_factor(A)
spLA.lu_solve((lu1, piv1), B)

array([2.        +4.44089210e-16j, 3.07246374+1.33729704e+00j,
       2.34980786+1.80701073e+00j, 2.20556128+2.00532585e+00j,
       2.16675826+2.10352326e+00j, 2.76309599+2.17010316e+00j,
       1.82603331+1.94018666e+00j, 1.2720806 +1.76734683e+00j,
       2.23784162+1.84214011e+00j, 2.2435935 +1.71908264e+00j,
       3.23068345+1.33376975e+00j, 5.        +0.00000000e+00j])

In [6]:
lu2, piv2 = spLA.lu_factor(A)
spLA.lu_solve((lu2, piv2), B)

array([2.        +4.44089210e-16j, 3.07246374+1.33729704e+00j,
       2.34980786+1.80701073e+00j, 2.20556128+2.00532585e+00j,
       2.16675826+2.10352326e+00j, 2.76309599+2.17010316e+00j,
       1.82603331+1.94018666e+00j, 1.2720806 +1.76734683e+00j,
       2.23784162+1.84214011e+00j, 2.2435935 +1.71908264e+00j,
       3.23068345+1.33376975e+00j, 5.        +0.00000000e+00j])

Now, I am going to define a function for LU factorization. This function is helpful for solution corresponding to tridiagonal matrices.

In [7]:

def LU_solve_tridiag(A, b):
    '''
    Function to solve matrix equation by LU factorization (efficient for tridiagonal matrices)
    Function: CFtriag(A, b)
        ARGUMENTS
    A, b: matrices for for equation, AX = b
        RETURNS
    X: solution of the matrix equation
    '''
    A_arr, b_arr = np.array(A), np.array([b])
    ab = np.concatenate((A_arr, b_arr.T), axis=1)
    n = len(ab)
    l = [[0 for j in range(n)] for i in range(n)]
    u = [[0 for j in range(n)] for i in range(n)]
    z = [0 for i in range(n)]
    for i in range(n-1):
        l[i][i-1] = ab[i][i-1]
        l[i][i] = ab[i][i] -l[i][i-1]*u[i-1][i]
        u[i][i+1] = ab[i][i+1]/l[i][i]
        z[i] = (ab[i][n]-l[i][i-1]*z[i-1])/l[i][i]
    l[n-1][n-2] = ab[n-1][n-2]
    l[n-1][n-1] = ab[n-1][n-1] -l[n-1][n-2]*u[n-2][n-1]
    z[n-1] = (ab[n-1][n]-l[n-1][n-2]*z[n-2])/l[n-1][n-1]
    X = [0 for i in range(n)]
    X[n-1] = z[n-1]
    for i in range(n-2, -1, -1):
        X[i] = z[i] - u[i][i+1]*X[i+1]
    return X

In [8]:
LU_solve_tridiag(A, B)

[(2+0j),
 (3.0724637363898277+1.3372970379232836j),
 (2.349807859936212+1.8070107266132946j),
 (2.205561276757351+2.005325848641847j),
 (2.166758256278089+2.1035232566126476j),
 (2.7630959922441964+2.170103164750727j),
 (1.8260333067077656+1.9401866591420722j),
 (1.2720806040962533+1.7673468297505694j),
 (2.2378416184081527+1.8421401131862254j),
 (2.2435934985172405+1.7190826440109177j),
 (3.2306834498904067+1.3337697475824486j),
 (5+0j)]